### ISSUE TITLE
Present focusing, clear, complete, and actionable error messages

### ISSUE THREAD

**Issue by StevenLocke** [k14s/ytt#291]
## Tasks
* [x] Ensure tests pass
* [x] for nil, print "null", not "<nil>"
* [ ] verify we've met the spirit of the acceptance criteria through some exploratory 'testing" — how would _you_ answer the questions from #285 ?

## Story

**As a** Configuration Author
**I want** — when my schema is invalid — helpful error messages
**so that** when I inevitably make mistakes, I can fix them quickly, ideally all by myself (increasing my confidence in the tool and my own skills with it)

and

**As a** Configuration Consumer
**I want** — when my data values do not conform to the schema — helpful error messages
**so that** when I inevitably make mistakes, I can fix them quickly, ideally all by myself (increasing my confidence in the tool and my own skills with it)

...

**where** "helpful error messages:"

1. focus my attention on the source of the problem,
1. gives _all_ of the relevant facts (and _none_ of the irrelevant ones)
1. consistently uses a set of accessible terms
1. makes clear what's wrong, and
1. helps me figure out how to fix it

## Context

https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ#Part-8-Command-Line-Interface-Interactions

-----

### General

Messages provided in this user story are intended to be _a thoughtful starting point_ rather than an _authoritative spec_.

Error messages should...

1. be formatted so as to be effortlessly parsed by the human eye
1. present the most important information in the most prominent location (i.e. where the eye goes first)
1. limit information to what's _directly_ relevant to the error
1. use the fewest words possible

### 🔴 Invalid schema

**Given** A schema that is well-formed YAML, but invalid Schema
**When** I invoke `ytt`
**Then** It reports an error including the location of the violation, the contents there, and the expectation that was not met.

_(hint: the test group_ `TestSchemaIsInvalidItFails` _in_ [`schema_test.go`](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/cmd/template/schema_test.go) _**ought** to enumerate all the ways in which Schema can be invalid.)_

#### Example 1a: Too many values defining the type of an array

`schema.yml:`
```yaml
#@schema/definition data_values=True
---
list:
- item 1
- item 2
```

```
$ ytt -f schema.yml -f data_values.yml --enable-experiment-schema
ytt: Error: ...

schema.yml:3 | list:
             |      ^^^
             |   found: 2 array items
             |   expected: exactly 1 array item
             |   (hint: to define an array, provide one item of the desired type; give default items in a separate data values document)
```

#### Example 1b: Not enough values defining the type of an array

`schema.yml:`
```yaml
#@schema/definition data_values=True
---
list: []
```

```
$ ytt -f schema.yml -f data_values.yml --enable-experiment-schema
ytt: Error: ...

schema.yml:3 | list:
             |      ^^^
             |   found: 0 array items
             |   expected: exactly 1 array item
             |   (hint: to define an array, provide one item of the desired type; the default value of arrays is an empty list)
```

#### Example 1c: Null value in schema 

`schema.yml:`
```yaml
#@schema/definition data_values=True
---
list: ~
```

```
$ ytt -f schema.yml -f data_values.yml --enable-experiment-schema
ytt: Error: ...

schema.yml:3 | list: ~
             |      ^^^
             |  expected: a non-null value, of the desired type
             |  (hint: to default to null, specify a value of the desired type and annotate with @schema/nullable)
```
Note: "hints" should...
- guard instructions on how to fix behind a guessed intent
- attempts to fill-in likely missing understanding
- contains words, that if used in a search would likely pinpoint relevant documentation

### 🔴 Type checking errors

**Given** a valid schema
**And** data values that do not conform to that schema
**When** I invoke `ytt`
**Then** it reports an error including: the location and line of the offending data value, the failed expectation, and the location in the schema where that expectation is expressed.

_(hint: the test group_ `TestDataValueNotConformingToSchemaFails` _in_ [`schema_test.go`](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/cmd/template/schema_test.go) _**ought** to enumerate all the ways in which Data Values can fail to conform to schema.)_

#### Example 2a: Schema specifies a string, Data Values contain a boolean

`schema.yml:`
```yaml
#@schema/definition data_values=True
---
address: ""
```

`data_values.yml:`
```yaml
#@data/values
---
address: false
```

```
$ ytt -f schema.yml -f data_values.yml --enable-experiment-schema
ytt: Error: ...

data_values.yml:3 | address: false
                  |          ^^^^^
                  |  found: boolean
                  |  expected: string (by schema.yml:3)
```
Note:
- the file the user is most likely editing (i.e. `data_values.yml`) is most prominently placed.
- ancillary (yet still relevant) information (e.g. which line in the schema) is tucked in a less prominent place.
- each piece of information's proximity is in proportion to its affinity with other pieces (what is "found" is in the `data_values.yml` file), so `found` comes first.

#### Example 2b: Data Values contain a map item key not declared in schema

`schema.yml:`
```yaml
#@schema/definition data_values=True
---
address: ""
```

`data_values.yml:`
```yaml
#@data/values
---
home_address: ""
```

```
$ ytt -f schema.yml -f data_values.yml --enable-experiment-schema
ytt: Error: ...

data_values.yml:3 | home_address: ""
                  | ^^^^^^^^^^^^
                  |   unexpected key in map (as defined at schema.yml:2)
                  |   (hint: did you mean "address"?)
```

## Implementation Notes

- consider defining a set of terms (taking into account, but not necessarily being bound by prior use of terms) before writing copy for error messages
- don't be bound by current means of accumulating error context (i.e. appending strings while popping up the call stack)
- we're still figuring out the best way to message errors to users; separate the concerns of what information is included with error messages from the presentation of those error messages.

**Comment by gcheadle-vmware** [comment]
Reopening since this is done but not released. This process is still being defined.

**Comment by pivotaljohn** [comment]
Okay, this was released, closing.
