### ISSUE TITLE
Release ytt 0.32.0

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#362]
This is a shared space to work through preparing the 0.32.0 release.

**To Do**
- [x] Identify all changes merged since 0.31.0 and ensure changes are properly documented and ready to merge:
  - [x] #264 - Warn users when a ytt template is provided but will not be included in output.
  - [x] #298 - Improve error message when overlaying docsets - fixes #297
  - [x] #301 - Append array items by default during overlay - fixes #269 
    - [x] https://github.com/vmware-tanzu/carvel.dev/pull/64 
    - [x] https://carvel.dev/ytt/docs/latest/faq/#how-do-i-add-items-to-an-existing-array
  - [x] #322 - Allow null values to be overlaid - fixes #108, #348
  - [x] #324 - Skip processing plain YAML files marked as template - fixes #232, #336  
    - [x] vmware-tanzu/carvel.dev#70
  - [x] #346 - arm64 build support - fixes #345 
    - [x] homebrew update?
  - [x] #369 - Using multiple file marks is now accepted - fixes #368
  - [x] Experimental Schema development
    - [x] #265 - Use schema file as a base for Data Values
    - [x] #279 - Provide error messages for schema violations - fixes #291 (not completely finished, waiting on #344)
    - [x] #319 - Use schema file in private libraries - fixes #296 
    - [x] #352 - Schema supports float types - fixes #292 
    - [x] #353 -  Schema type-checks command line data values - fixes #333 (not completely finished, waiting on #344)
- [x] Check back in on [the Slack conversation about cutting this release](https://kubernetes.slack.com/archives/CH8KCCKA5/p1618852472366100)
- [x] When all is ready, follow our release process

**Comment by gcheadle-vmware** [comment]
# :sparkles: What's new
- Array items are appended by default during overlay [#301](https://github.com/vmware-tanzu/carvel-ytt/pull/301)
- Allow null values to be overlayed [#322](https://github.com/vmware-tanzu/carvel-ytt/pull/322)
- Skip processing plain YAML files marked as template [#324](https://github.com/vmware-tanzu/carvel-ytt/pull/324)
- arm64 architecture support, binaries included below [#346](https://github.com/vmware-tanzu/carvel-ytt/pull/346)
- Experimental schema support: #103
    - Use feature flag --enable-experiment-schema to enable
    - Use schema file as a base for Data Values #265
    - Support using schema in ytt libraries #269
    - Schema supports float types #352
    - Schema type-checks command line data values #353
    - For those curious, check out schema_test.go for details of what exactly is supported
 
# 🚀 Improvements
- Add warning when non YAML file is provided without output options [#264](https://github.com/vmware-tanzu/carvel-ytt/pull/264)
- Improved error message when overlaying docsets [#264](https://github.com/vmware-tanzu/carvel-ytt/pull/264)
- Support multiple exclude file marks [#369](https://github.com/vmware-tanzu/carvel-ytt/pull/369) 

# :speaker: Callouts
- Added informational ytt YouTube video to README: Adrian Sales @adriens

# :open_file_folder: Files Checksum
```
bfd60b38f74fd532e99cff2d2d309aea1b1e00d9d5faaf414ebd30ea9c1a7a43  ./ytt-darwin-amd64
42470495f35fbbe66a0c40ab516519839448475e0e24477b1f33f69d38834175  ./ytt-darwin-arm64
1a8f30e0b86b9daa649433e6092a4a1c6fc9c88400b6842af357c7380924bbc6  ./ytt-linux-amd64
95e5bf9c1c4d972edfa656311ed3ce6b6d745638aad94003bee5807736fe32e3  ./ytt-linux-arm64
bfe937df42faa81e42c49bab3e68e836eae981d7591669f410d2bbf1d2d71bae  ./ytt-windows-amd64.exe
```

**Comment by gcheadle-vmware** [comment]
All items followed up on, closing issue.
